apiVersion: v1
kind: Namespace
metadata:
  name: feast

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-sa
  namespace: feast

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast-data
  namespace: feast
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
