---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: serving-minio-creds
  namespace: serving
spec:
  encryptedData:
    aws-access-key-id: AgAZzKrhQobhyNwvXFMB+6o8i60qwF4osVMD3JMmwmc0HrH5LwOrN+zps1Pm/AsaBTDu5q/rvGN0dQEVspNFC8AIs+Iy1AT+6r5tUybACLdwRXiKrC4as2qKXg5SjTAzpmCNEMvwlWQ2NozxXA62EX6599OaxLE76AnrStSk/k4pGdqfoF6yiBgoCbQGYhqdIz9SAsXS38bscn5nMkGFlrxAAChbh35WILTCAk+fQfxbBU48WySiXj/baI6qHndPt/xDhifYSNcozavtUkNOfJLpsZ8c7QEcNoJmwOaGyLn6Lu3JaEMwU0zQNNzBiksefpNjuN3jZbKdU8a8cX8Jfc/REXRGZA3lBTSWJG0WPY7T7C6/8Y2f12KhiF2xjVQkQ/ExQfoXqg4KNzzUW9oE8oD58WfiIAMizR6luyuElQVlEA+PmKq6L88lskjkmu6JRz/Y78wg4NzTQPEwvq/viL5JcXHjIb2sKo0Wp2NKcNqUrh+oXhUuPScQcSVPqTLaD+sJ6OnaxisMNpK1rAALeceOmWKje23ILD0PgJU9A5jpHwdBtR5NI8ch799t9EYIWyAGdf/c4LZbFCSZru3T3oKeIX9iR2KYlZ41xVRJ5e9f/onywvAXrKUQPKRDY3611RstYB90KS7jhDVVXNv31xeyp/Kz+RyiQqb/NfYW5cvzHde89pCksFCgWe4UV8XNIDc1ySlvgEX8W6AO
    aws-secret-access-key: AgBR2723sgbnWbCJbS7YVxJF8/R5ngsCbRHaQfhLLd8oDfnUkPW1bpWkJA//N8QifRjgWqPwipmwIHaJo97LYWFdTcySun6DSaxGrk+4d9qJCRaHwNTOpCzmgMfvC+ma7HX8gXgjiEa/aXy7rgsT6crYmhbkA1Dxta+iMwdep8CHyyOgUoyFVkvO72pYBKwTeMl6K+yy8yN6wzbwfk3Lrg/vDt9yB7WwoewufkEk8dzsC8Olr3jyocxVQlZ6y+MiHp62Q5C9g5feM0lRG8bUjO5E7RAL2e+XHTre0SwboOfxZET1JplTXVDx7oonmU0fs493QK6UnweHW1JK9ZPqMpPfp8ZxxpNcMDB72PaVFh6rJZZ19hMNq9ToQjpz2NTJFnjKAPGz+G13HuQFwz6cf9Gq5rShCtEo2eB4pBy73Fx7aAmdj6+QS0BaPLlGnprZk0W4dnvfQkBsQ8Y1RN6teDs5Rpro1zHUyJPx+MAs13jVf3XQ8uT3A9rSV8HJOlvxENcY6ksvArOJ/+ta7cKqAbrtwC/VVF1U/7Qe3/LPm/trLMGp1lVQes9cfT21SpCTMhOstbM5mKcFF63Ckfygm3f1/dDS+OgMc7k/jz7Kh6RTvPWwqU8KN3gYthm0HqkD4bBTGx4lSc1UW7RkR54jJzB79fMyOI3fow6ZznQ1ZeyGfQcC/cJG04rrz7OLd6ddwZ15ZJbLJxoz34kt
  template:
    metadata:
      name: serving-minio-creds
      namespace: serving
