FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.115.0 \
    uvicorn==0.30.0 \
    mlflow==2.19.0 \
    scikit-learn==1.6.1 \
    pandas==2.2.3 \
    boto3==1.42.59 \
    psycopg2-binary==2.9.11

COPY src/serving/ ./src/serving/

CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8080"]
