---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    root-password: AgA/LISytE0kr3st0r5j1Z2wUeQ4DBRCiaq560tCHdx4vI60WGJgQCcWXSwbOqPJcPkoNe8yBGW0lELNneWIJ4IXZU+BJgH4PZ3iZgjV0pxiVdf8xOAj49C70o5fp+uIp8rIPn4fjW2NHplju+dXDfAYHG7QGPZRhqLVpz32HMtfv3pXDdXUZbfHqpxWPJLeQkI1sQ3iEyCIW6d5mWQehxc0yOhcDACwGYAqGej7/MmP5Z/PqwUBhsKv0Gs8xooQwgSDtSISumid5YhfPVhisKLpDmVidFMs3eTWsO0CRi6GnWKkPmTAY0BmRq+Xx6ekzPOABce2LuSfo+voHoE+5Uvss/BS1b1lyvqtigmbpGq9d34noRoJJ0jNOm5hKA9/v/8+J3yPWQkMcKDr/GJILyuDzWMwvsw/OOApse2SQexqQjKP+Cmrox4akBOm0kLnyDU8aDbvFCDveLko2WznNaRI4x0+26HnmEWE6wMVNKVD7ioiJJKlHqomlT/atHvdW5BgyNEg8hW2qeSeq9CIzP/iHKD7SeG7lokSFzOtGjNj4vIYidts2YVqr+nfzfHHA8qF/Vse5zO2TpAmiE+VR0MYkkzJOjs8YwX+q+Qi+dXLiO8nYlqdFc8BLl7oCztOOW5rCjpswZ7m9nJrqmUGXpOQVb/US5kav+2PrtOAAgE1tb/Ghe4r0pCdyRL0D3jn1/dhmm2bqRVQ0Csk
    root-user: AgCXb9fv2AhdtiGSFLPu/eVO6cVh2GwjzGpig64zPMbYNjmUEdRqPi0HnB1pJcSnr7TZa27ZmBfaPlW01bn4kgrg/U5BoZOQZ7CrrRk0nt/9A7628BWHUlhKwE03droKdfJu4EFOrameH50BDCNJrIwUODfplzNTc/vIATLcgD5oE/gxkWByCbfl4tJwsntgjkaljuu7m0qf+7TBfvrIhFCEXDCMC9KCq8iGqYgcViUjYDzHufTWDhGt6s0vVKvLQAZlB0Ib/A+0u4zsexQNzZO94BjnLCjjcL5EbXihjxomPl9klDxFEFHJBhC9FkxF12zAQHS1EA2q4RPTXzfvKXFQ01ePIYhAD0qnSsRjPTcx4yAwRuu6W6D1HxuJH+JNhHIH35iSpJ6uXOkY5632fYtqGbLpp93lZpW2hHYOtpQ5yIp5lTzUMBPkDNSsTiezgkLcgtfM4SryJgVEFAqnaBOD6ut5JWEbu6kgMAryjERbXjXpVlKi5pTFtBPCnLHLVEHcFhfda0TRh/2NeU1L83taDyYOuKY2YfcMblFSiAd/XEyLq+K9RigMfL7I41roUmjl92+UQbL5pf9f0yTNvjUNHIY3eKg/cE5PYtNTttivqM+Jas2+V4vVa7xH1xZGGy+pppuaePDERhZXl1LJk21BVzFPM+vQi5zHclPm+3UA2STWtLHDi8uJHiOOw8YoWU97GETWl200b1+Q
  template:
    metadata:
      name: minio-creds
      namespace: minio
