---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-credentials
  namespace: airflow
spec:
  encryptedData:
    password: AgBZfMPIT/oDAp560O6iVLyyTqT1HtVNfiJkRMOLHWdWHDeQhvzhDW7q6Kl3C5H7pZ9gpZW7vYUsPcfsGFYrUrPr5ugRCuiiOtXrrQycCqCjGxGot7ahyUHjWhSGsirJttmYsRBYTpjCHTUfp6x4qMHawALUuNGISyGlBjjs6JyzU6zlyjY52LPiyvqpCGj9yCkRu4Bqor5MiiYivocduyaKm8CR6qPkTJEL3aVUERaEGU+9T4/2zoUcLj4doigX/4q61UZaqUqBfGkPiyXVanDalhJxrBMbNwaChNqITyL3kocv5K4Iq8bEWNCvoYyFhPsHfr6ZXMKtrVM4f0HBHv1U+X8Xfk1DLEwXZVz02CNiX3E7JgIpzfPxEeLsAFpVv0JdBTgDabc34V+YPOOdRxnEEQAHxesYDP8aXjR3whgNvb4C2IQI74gNgaOrk1as2fKDf+7V8AaLFv+bqhym/0N5R6RmHsDWGbGjTZSeOZW/f+B7R+TGrARrPsbwxkjn/9J4GmaHaUoHq8PgeZnRT7myyMRSkTAlr5FB/r6th76xa6avJZLydrR/4boKPKbVBe+nWpwwociSMw9/JeVcitVJqM9tGyxuyhFnESENBBAQrOo/nB2L+nL+WMECp7RwsG3Tvrau63+uKgjtrJ4Cd74OntmCd9wCggql6EPIBCJ4we9ZzjTJP5iZNAVPZyJTserGqMUc
    username: AgA9ndsdbdBGqYHlf3Pd7MINwwM55whvFQ1bXi/POuivi27hHWn/aDJ8adXW0mv4+qzydnDe80zWs0zMJSqGTOGiIyKGZky9EVnM59w8mup5v+HkOFesxWhLAdYXg7me2tXfrp+1X+GPcO5jIa9OQv7igsNZBB7aEeYhPcXYmP27KSqP18zkG7DzC0QgdLoDQC8Tqtqyn2d2GqXLCGqFsgswaTO0ALm4MU8NBr6/jQDDRgIOrTMZSy/KW8NWVRruF/na3AmvhesXQG05wzxO3R8wYAwk7TefcbrN4mvk090XgL2Dhz4eJfLBWgvQQcxsFTuh2IFU/BxI8cPQrI4md7tpXRoMZ9dcaG3VAmYtS/x0EfJNYpaHToc0orlzJpJeniNNZx8+vI5admduZ9Ow6zLB8dON72h4A5KBqTOFRD7UCceRW7+Lb/+HL9vO71+3aecrqplKLeVBuEHlKmwW1TmgTs/ufKXBZwmPZtc6d0aeZYqCllSz2lewpbr73V2an4sasnmTzpWWvETJ/u1qyN3FRERG9FquWBbgI+XXvjVBGCQEABjVwNZ0RHv5mW1QMwZNsEA/1l8nc/rQEjiI4xcAgWnREw1pG3A3NdkG2ECpADYspg1cLNQ7YiTs16uWtnpe+9mAD/fEikPS+xQTTAfrMLqAQwfdXcsAz8AlZMSdZfWwPEvXjZwmEuyJWC0iwLb61c5V
  template:
    metadata:
      name: git-credentials
      namespace: airflow
